import Chart from "react-apexcharts";
import Loading from "../../components/ui/Loading";
import { useGetDatesAndValues } from "../../hooks/useGetDatesAndValues";
import { useGetStatisticsQuery } from "../../redux/api/baseApi";

const PieChart = () => {
  const { data: statistics, isLoading } = useGetStatisticsQuery({});

  // Call the hook unconditionally
  const { dates = [], values = [] } = useGetDatesAndValues(statistics || []);

  // If the data is still loading, return the Loading component
  if (isLoading) {
    return <Loading />;
  }

  // If there is no data, show a message
  if (!statistics || dates.length === 0 || values.length === 0) {
    return <div>No data available</div>;
  }

  return (
    <div className="min-h-screen flex justify-center items-center">
      <Chart
        type="pie"
        width={800}
        height={500}
        series={values}
        options={{
          chart: {
            animations: {
              enabled: true,
              easing: "easeinout",
              speed: 800,
            },
            toolbar: { show: false },
          },
          title: {
            text: "Statistics of Earning in Every Month",
            style: {
              fontWeight: 600,
              fontSize: "18px",
            },
          },
          subtitle: {
            text: "Generated by AAK Team",
            style: {
              fontSize: "15px",
            },
          },
          labels: dates,
          states: {
            hover: {
              filter: {
                type: "darken",
                value: 0.5,
              },
            },
          },
          tooltip: {
            enabled: true,
            y: {
              formatter: (val) => {
                return `$${val}`;
              },
            },
          },
          legend: {
            position: "right",
            horizontalAlign: "center",
            floating: false,
            itemMargin: {
              horizontal: 10,
              vertical: 8,
            },
            fontSize: "16px",
            fontWeight: 400,
          },
          responsive: [
            {
              breakpoint: 600,
              options: {
                chart: {
                  width: 340,
                },
                legend: {
                  position: "bottom",
                  fontSize: "14px",
                },
                title: {
                  style: {
                    fontSize: "14px",
                  },
                },
                subtitle: {
                  style: {
                    fontSize: "12px",
                  },
                },
              },
            },
            {
              breakpoint: 900,
              options: {
                chart: {
                  width: 600,
                },
              },
            },
          ],
        }}
      />
    </div>
  );
};

export default PieChart;
