import Chart from "react-apexcharts";
import { useGetStatisticsQuery } from "../../redux/api/baseApi";
import { TYearData } from "../../types/barChartType";
import { formattedDate } from "../../utils/formattedDate";
import Loading from "../ui/Loading";

const BarChart = () => {
  const { data: statistics, isLoading } = useGetStatisticsQuery({});

  if (isLoading) {
    return <Loading />;
  }

  const dates: string[] = [];
  const values: number[] = [];

  const processChartData = (chartData: TYearData[]) => {
    chartData.forEach((yearData) => {
      const years = Object.keys(yearData);

      years.forEach((year) => {
        yearData[year].forEach((monthData) => {
          Object.keys(monthData).forEach((month) => {
            monthData[month].forEach((dayData) => {
              const dayDataArr = Object.entries(dayData)[0];

              const [dateString, value] = dayDataArr;

              const formatDate = formattedDate(dateString);

              dates.push(formatDate);
              values.push(value);
            });
          });
        });
      });
    });
  };

  processChartData(statistics);

  //   console.log(dates);
  //   console.log(values);

  return (
    <div>
      <Chart
        type="bar"
        width={640}
        height={450}
        series={[{ name: "Earning", data: values }]}
        options={{
          chart: {
            animations: {
              enabled: true,
              easing: "easeinout",
              speed: 800,
            },
            toolbar: { show: false },
          },
          title: {
            text: "Statistics of Earning in Every Month",
            style: {
              fontWeight: 600,
              fontSize: "20px",
            },
          },
          subtitle: {
            text: "Generated by AAK Team",
            style: {
              fontSize: "15px",
            },
          },
          colors: ["#0095CF"],
          xaxis: {
            categories: dates,
            title: {
              text: "Month Name",
              style: {
                fontSize: "14px",
                fontWeight: "600",
                cssClass: "custom-title",
              },
            },
          },
          yaxis: {
            labels: {
              //   formatter: (val) => {
              //     return `$${val}`;
              //   },
              style: {
                fontSize: "14px",
              },
            },
            title: {
              text: "Counting Amount!",
              style: {
                fontSize: "14px",
                fontWeight: "600",
                cssClass: "custom-title",
              },
            },
          },
          plotOptions: {
            bar: {
              borderRadius: 4,
              distributed: true,
            },
          },
          states: {
            hover: {
              filter: {
                type: "darken",
                value: 0.6,
              },
            },
          },
          fill: {
            colors: [
              "#00E396",
              "#FEB019",
              "#FF4560",
              "#775DD0",
              "#008FFB",
              "#F9A3A4",
            ],
            // opacity: 1,
          },
          tooltip: {
            enabled: true,
            y: {
              formatter: (val) => {
                return `$${val}`;
              },
            },
          },
          legend: { show: false },
          dataLabels: {
            enabled: false,
            // formatter: (val) => {
            //   return `$${val}`;
            // },
          },
          responsive: [
            {
              breakpoint: 600,
              options: {
                chart: {
                  width: 340,
                },
                legend: {
                  position: "bottom",
                },
                title: {
                  style: {
                    fontSize: "14px",
                  },
                },
                subtitle: {
                  style: {
                    fontSize: "12px",
                  },
                },
              },
            },
          ],
        }}
      />
    </div>
  );
};

export default BarChart;
